name: Kits
main: org.Dragonphase.Kits.Kits
version: 1.01
website: http://dragonphase.com/
depend: []
description: >
             Kits plugin.
commands:
  kits:
    description: Kits help
  kit:
    description: Kits help
permissions:
  kits.reload:
    description: Allows players to reload Kits
    default: op